### ISSUE TITLE
dangerous script

### ISSUE THREAD

**Issue by haitham11** [aliostad/deep-learning-lang-detection#1]
be careful when working with this project. You should only read the text content of the code and never run it  because contains this file 370d9237a2ae3993d9ced152970e89f7b8635985Get-WLAN-Keys.ps1  which is a dangerous script from nishang test suite.
And I think the problem will be solved and the file will be deleted in the few next days.

**Comment by aliostad** [comment]
Thank you very much for raising this. I am going to remove it.

**Comment by aliostad** [comment]
There were 3 files. All deleted.
